In [1]:
from warnings import filterwarnings
filterwarnings('ignore')

In [2]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt 
%matplotlib inline

In [3]:
df = pd.read_csv("./car+evaluation/Car_Evaluation_final.csv")

In [4]:
df.head()

doors  persons  buying  maint  lug_boot  safety  class values
0      2        2     3.0    3.0       2.0     1.0           2.0
1      2        2     3.0    3.0       2.0     2.0           2.0
2      2        2     3.0    3.0       2.0     0.0           2.0
3      2        2     3.0    3.0       1.0     1.0           2.0
4      2        2     3.0    3.0       1.0     2.0           2.0

## Spliting Independent and Dependent Variable

In [5]:
X = df.drop(['class values'],axis=1)
y = df['class values']

In [6]:
X.head()

doors  persons  buying  maint  lug_boot  safety
0      2        2     3.0    3.0       2.0     1.0
1      2        2     3.0    3.0       2.0     2.0
2      2        2     3.0    3.0       2.0     0.0
3      2        2     3.0    3.0       1.0     1.0
4      2        2     3.0    3.0       1.0     2.0

In [26]:
y.value_counts()

class values
2.0    1210
0.0     384
1.0      69
3.0      65
Name: count, dtype: int64

In [7]:
y.head()

0    2.0
1    2.0
2    2.0
3    2.0
4    2.0
Name: class values, dtype: float64

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, ytrain, ytest = train_test_split(X,y, test_size=0.20, random_state=42)

In [9]:
X_train.shape, X_test.shape

((1382, 6), (346, 6))

In [10]:
ytrain.shape, ytest.shape

((1382,), (346,))

In [21]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(multi_class='multinomial',solver='lbfgs')

In [22]:
model.fit(X_train,ytrain)

LogisticRegression(multi_class='multinomial')

In [23]:
y_pred = model.predict(X_test)
y_pred

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 0., 2., 2., 2., 2., 2., 2.,
       2., 2., 0., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       0., 2., 2., 0., 0., 2., 2., 0., 2., 2., 2., 0., 2., 2., 2., 2., 3.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 0., 2., 2.,
       0., 2., 2., 2., 2., 2., 2., 0., 0., 2., 2., 2., 2., 2., 2., 2., 0.,
       2., 2., 2., 0., 3., 2., 0., 2., 2., 2., 0., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 0., 2., 0., 0., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 0., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 0.,
       2., 0., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 0., 2., 2., 2., 2., 2., 2., 0., 2.,
       2., 2., 2., 0., 0., 0., 2., 2., 2., 0., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 0., 2.

In [24]:
ytest

599     2.0
1201    0.0
628     2.0
1498    0.0
1263    2.0
       ... 
100     2.0
274     2.0
1206    2.0
101     2.0
1084    2.0
Name: class values, Length: 346, dtype: float64

In [25]:
## Confuaion Metrics Accuracy , Classificaton report

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

print(confusion_matrix(y_pred,ytest))
print(accuracy_score(y_pred,ytest))
print(classification_report(y_pred,ytest))

[[ 12   2  17  12]
 [  0   0   0   0]
 [ 68   9 217   5]
 [  3   0   1   0]]
0.661849710982659
              precision    recall  f1-score   support

         0.0       0.14      0.28      0.19        43
         1.0       0.00      0.00      0.00         0
         2.0       0.92      0.73      0.81       299
         3.0       0.00      0.00      0.00         4

    accuracy                           0.66       346
   macro avg       0.27      0.25      0.25       346
weighted avg       0.82      0.66      0.73       346

