In [1]:
from warnings import filterwarnings
filterwarnings('ignore')

In [2]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/neerajprasad209/Dataset/main/iris.csv")

In [4]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
df['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [6]:
df[df['species'] == 'setosa']

sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
16           5.4          3.9           1.3          0.4  setosa
17           5.1          3.5           1.4          0.3  setosa
18           5.7          3.8           1.7          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa
20           5.4          3.4           1.7          0.2  setosa
21           5.1          3.7           1.5          0.4  setosa
22           4.6          3.6           1.0          0.2  setosa
23           5.1          3.3           1.7          0.5  setosa
24           4.8          3.4           1.9          0.2  setosa
25           5.0          3.0           1.6          0.2  setosa
26           5.0          3.4           1.6          0.4  setosa
27           5.2          3.5           1.5          0.2  setosa
28           5.2          3.4           1.4          0.2  setosa
29           4.7          3.2           1.6          0.2  setosa
30           4.8          3.1           1.6          0.2  setosa
31           5.4          3.4           1.5          0.4  setosa
32           5.2          4.1           1.5          0.1  setosa
33           5.5          4.2           1.4          0.2  setosa
34           4.9          3.1           1.5          0.2  setosa
35           5.0          3.2           1.2          0.2  setosa
36           5.5          3.5           1.3          0.2  setosa
37           4.9          3.6           1.4          0.1  setosa
38           4.4          3.0           1.3          0.2  setosa
39           5.1          3.4           1.5          0.2  setosa
40           5.0          3.5           1.3          0.3  setosa
41           4.5          2.3           1.3          0.3  setosa
42           4.4          3.2           1.3          0.2  setosa
43           5.0          3.5           1.6          0.6  setosa
44           5.1          3.8           1.9          0.4  setosa
45           4.8          3.0           1.4          0.3  setosa
46           5.1          3.8           1.6          0.2  setosa
47           4.6          3.2           1.4          0.2  setosa
48           5.3          3.7           1.5          0.2  setosa
49           5.0          3.3           1.4          0.2  setosa

## Transform species into ordinal encoder

In [7]:
from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder()

In [8]:
encode = encoder.fit_transform(df[['species']])

In [9]:
df['species'] = pd.DataFrame(encode,columns=encoder.get_feature_names_out())

In [10]:
df.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2      0.0
1           4.9          3.0           1.4          0.2      0.0
2           4.7          3.2           1.3          0.2      0.0
3           4.6          3.1           1.5          0.2      0.0
4           5.0          3.6           1.4          0.2      0.0

In [13]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

## Spliting Independent and Dependent Variable

In [14]:
from sklearn.model_selection import train_test_split

X_train,X_test,ytrain,ytest = train_test_split(X,y, test_size=0.20, random_state=20)

In [18]:
X_train.shape, X_test.shape

((120, 4), (30, 4))

In [17]:
ytrain.shape, ytest.shape

((120,), (30,))

In [19]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(multi_class='multinomial',solver='lbfgs')

In [20]:
model.fit(X_train,ytrain)

LogisticRegression(multi_class='multinomial')

In [25]:
y_pred = model.predict(X_test)

In [26]:
ytest

47     0.0
73     1.0
74     1.0
129    2.0
67     1.0
89     1.0
143    2.0
21     0.0
108    2.0
12     0.0
147    2.0
76     1.0
119    2.0
35     0.0
28     0.0
122    2.0
13     0.0
58     1.0
114    2.0
57     1.0
50     1.0
149    2.0
111    2.0
20     0.0
72     1.0
81     1.0
98     1.0
34     0.0
104    2.0
133    2.0
Name: species, dtype: float64

In [28]:
## Confuaion Metrics Accuracy , Classificaton report

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

print(confusion_matrix(y_pred,ytest))
print(accuracy_score(y_pred,ytest))
print(classification_report(y_pred,ytest))

[[ 8  0  0]
 [ 0 11  2]
 [ 0  0  9]]
0.9333333333333333
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00         8
         1.0       1.00      0.85      0.92        13
         2.0       0.82      1.00      0.90         9

    accuracy                           0.93        30
   macro avg       0.94      0.95      0.94        30
weighted avg       0.95      0.93      0.93        30

