In [10]:
from warnings import filterwarnings
filterwarnings('ignore')

In [11]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 

%matplotlib inline

In [12]:
df = pd.read_csv('./fertility.csv')

In [13]:
df.head()

Season  Age Childish_diseases Accident_or_serious_trauma  \
0  spring   30                no                        yes   
1  spring   35               yes                         no   
2  spring   27               yes                         no   
3  spring   32                no                        yes   
4  spring   30               yes                        yes   

  Surgical_intervention High_fevers_in_the_last_year  \
0                   yes       more than 3 months ago   
1                   yes       more than 3 months ago   
2                    no       more than 3 months ago   
3                   yes       more than 3 months ago   
4                    no       more than 3 months ago   

  Frequency_of_alcohol_consumption Smoking_habit  \
0                      once a week    occasional   
1                      once a week         daily   
2             hardly ever or never         never   
3             hardly ever or never         never   
4                      once a week         never   

   Number_of_hours_spent_sitting_per_day Diagnosis  
0                                     16    Normal  
1                                      6   Altered  
2                                      9    Normal  
3                                      7    Normal  
4                                      9   Altered

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column                                 Non-Null Count  Dtype 
---  ------                                 --------------  ----- 
 0   Season                                 100 non-null    object
 1   Age                                    100 non-null    int64 
 2   Childish_diseases                      100 non-null    object
 3   Accident_or_serious_trauma             100 non-null    object
 4   Surgical_intervention                  100 non-null    object
 5   High_fevers_in_the_last_year           100 non-null    object
 6   Frequency_of_alcohol_consumption       100 non-null    object
 7   Smoking_habit                          100 non-null    object
 8   Number_of_hours_spent_sitting_per_day  100 non-null    int64 
 9   Diagnosis                              100 non-null    object
dtypes: int64(2), object(8)
memory usage: 7.9+ KB


In [14]:
df['Season'].value_counts()

Season
spring    37
fall      31
winter    28
summer     4
Name: count, dtype: int64

In [15]:
df.columns

Index(['Season', 'Age', 'Childish_diseases', 'Accident_or_serious_trauma',
       'Surgical_intervention', 'High_fevers_in_the_last_year',
       'Frequency_of_alcohol_consumption', 'Smoking_habit',
       'Number_of_hours_spent_sitting_per_day', 'Diagnosis'],
      dtype='object')

In [29]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df.Season = le.fit_transform(df.Season.values)
df.Childish_diseases = le.fit_transform(df.Childish_diseases.values)
df.Accident_or_serious_trauma = le.fit_transform(df.Accident_or_serious_trauma.values)
df.Surgical_intervention = le.fit_transform(df.Surgical_intervention.values)
df.High_fevers_in_the_last_year = le.fit_transform(df.High_fevers_in_the_last_year.values)
df.Frequency_of_alcohol_consumption = le.fit_transform(df.Frequency_of_alcohol_consumption.values)
df.Smoking_habit = le.fit_transform(df.Smoking_habit.values)
df.Diagnosis = le.fit_transform(df.Diagnosis.values)


In [30]:
df.head()

Season  Age  Childish_diseases  Accident_or_serious_trauma  \
0       1   30                  0                           1   
1       1   35                  1                           0   
2       1   27                  1                           0   
3       1   32                  0                           1   
4       1   30                  1                           1   

   Surgical_intervention  High_fevers_in_the_last_year  \
0                      1                             1   
1                      1                             1   
2                      0                             1   
3                      1                             1   
4                      0                             1   

   Frequency_of_alcohol_consumption  Smoking_habit  \
0                                 2              2   
1                                 2              0   
2                                 1              1   
3                                 1              1   
4                                 2              1   

   Number_of_hours_spent_sitting_per_day  Diagnosis  
0                                     16          1  
1                                      6          0  
2                                      9          1  
3                                      7          1  
4                                      9          0

In [32]:
X = df.drop('Diagnosis',axis=1)
y = df['Diagnosis']

In [33]:
X.head()

Season  Age  Childish_diseases  Accident_or_serious_trauma  \
0       1   30                  0                           1   
1       1   35                  1                           0   
2       1   27                  1                           0   
3       1   32                  0                           1   
4       1   30                  1                           1   

   Surgical_intervention  High_fevers_in_the_last_year  \
0                      1                             1   
1                      1                             1   
2                      0                             1   
3                      1                             1   
4                      0                             1   

   Frequency_of_alcohol_consumption  Smoking_habit  \
0                                 2              2   
1                                 2              0   
2                                 1              1   
3                                 1              1   
4                                 2              1   

   Number_of_hours_spent_sitting_per_day  
0                                     16  
1                                      6  
2                                      9  
3                                      7  
4                                      9

In [34]:
y.head()

0    1
1    0
2    1
3    1
4    0
Name: Diagnosis, dtype: int32

In [39]:
from sklearn.model_selection import train_test_split

Xtrain, Xtest, ytrain, ytest =  train_test_split(X,y, test_size=0.10, random_state=12)

In [40]:
Xtrain.shape, Xtest.shape

((90, 9), (10, 9))

In [41]:
ytrain.shape, ytest.shape

((90,), (10,))

In [42]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression()

In [43]:
classifier.fit(Xtrain,ytrain)

LogisticRegression()

In [44]:
classifier.predict_proba(Xtest)

array([[0.2399115 , 0.7600885 ],
       [0.02709809, 0.97290191],
       [0.07156153, 0.92843847],
       [0.2976219 , 0.7023781 ],
       [0.06712693, 0.93287307],
       [0.13039445, 0.86960555],
       [0.07574619, 0.92425381],
       [0.11088926, 0.88911074],
       [0.52228222, 0.47771778],
       [0.08996612, 0.91003388]])

In [45]:
ypred = classifier.predict(Xtest)

In [46]:
ypred

array([1, 1, 1, 1, 1, 1, 1, 1, 0, 1])

In [47]:
ytest

17    0
41    1
92    1
14    1
68    1
31    1
89    1
15    1
21    1
60    1
Name: Diagnosis, dtype: int32

In [48]:
## Confuaion Metrics Accuracy , Classificaton report

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

print(confusion_matrix(ypred,ytest))
print(accuracy_score(ypred,ytest))
print(classification_report(ypred,ytest))

[[0 1]
 [1 8]]
0.8
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.89      0.89      0.89         9

    accuracy                           0.80        10
   macro avg       0.44      0.44      0.44        10
weighted avg       0.80      0.80      0.80        10

